###
# 선거구
GET http://13.209.167.197//api/v1/voting_districts?page=1&per=10
Content-Type: application/json
device-id: 851aea3865656f8c

###
# 선거구
GET http://13.209.167.197//api/v1/voting_districts?page=1&per=10&keyword=민정
Content-Type: application/json
device-id: 851aea3865656f8c

###
# 선거구
GET http://13.209.167.197//api/v1/voting_districts?x=127.2893717&y=37.3942133
Content-Type: application/json
device-id: 851aea3865656f8c

###
# 선거구
GET http://13.209.167.197//api/v1/voting_districts?x=126.9305023&y=37.4030928
Content-Type: application/json
device-id: 851aea3865656f8c

###
# 선거구
GET http://13.209.167.197/api/v1/district_by_location?x=126.9305023&y=37.4030928
Content-Type: application/json
device-id: 851aea3865656f8c

###
# 선거구
GET http://13.209.167.197//api/v1/candidates?page=1&per=10
Content-Type: application/json
device-id: 851aea3865656f8c

###
# 선거구
GET http://13.209.167.197//api/v1/voting_districts/148
Content-Type: application/json
device-id: 851aea3865656f8c


###
GET https://openapi.naver.com/v1/search/news.json?query=총선&start=2&display=20
X-Naver-Client-Id: cS1YcI9G0x81SoULqK9X
X-Naver-Client-Secret: 3nQp_BdUL7


###
# 게시판
GET http://13.209.167.197/api/v1/boards
Content-Type: application/json
device-id: 851aea3865656f8c