


###
# user create 
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "data": {
    "device_id": "1110115",
    "age": 50,
    "sex": "man",
    "latitude": 100,
    "longitude": 200
  }
}

###
# 도시 
GET http://localhost:3000/api/v1/cities?page=1&per=10
Content-Type: application/json


###
# 선거구 
GET http://localhost:3000/api/v1/voting_districts?page=1&per=10
Content-Type: application/json



###
# 후보 
GET http://localhost:3000/api/v1/candidates?page=1&per=10
Content-Type: application/json





