@server = http://localhost:3000
# @server = http://13.209.167.197

###
# user create 
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "data": {
    "device_id": "1110115",
    "age": 50,
    "sex": "man",
    "longitude": 126.973457,
    "latitude": 37.555465
  }
}

###
# 도시 
GET {{server}}/api/v1/cities?page=1&per=10
Content-Type: application/json

###
# 선거구 
GET {{server}}/api/v1/voting_districts?page=1&per=10
Content-Type: application/json

###
# 후보 
# GET {{server}}/api/v1/candidates?page=1&per=10&x=126.973457&y=37.555465
GET {{server}}/api/v1/candidates?page=1&per=10&x=126.973457&y=37.555465
Content-Type: application/json


###
GET https://dapi.kakao.com/v2/local/geo/coord2address.json?x=126.973457&y=37.555465
Authorization: KakaoAK aaebc65e6dd5021b19da8251a4b2adc9





