@server = http://localhost:3000
@device-id= 1110115

# @server = http://api.v2020.ownerz.io
# @server = http://13.209.167.197
# @device-id= 9cb1bac632cd3bfd

# @server = http://ssm-imgproxy-qav1.ap-northeast-2.elasticbeanstalk.com
# @device-id= 9cb1bac632cd3bfd


###
# user show 
GET {{server}}/api/v1/sessions
Content-Type: application/json
device-id: {{device-id}}

###
# user create 
POST {{server}}/api/v1/users
Content-Type: application/json
device-id: {{device-id}}

{
  "data": {
    "age": 0,
    "sex": 0
  }
}

### 
# like candidate
PUT {{server}}/api/v1/users/likes
# PUT {{server}}/api/v1/candidates/likes
Content-Type: application/json
device-id: {{device-id}}

{
  "data": {
    "candidate_id": 19
  }
}

###
# liked candidates
GET {{server}}/api/v1/users/likes
# GET {{server}}/api/v1/candidates/likes
Content-Type: application/json
device-id: {{device-id}}


###############################################
### 
# create comment 
POST {{server}}/api/v1/candidates/18/comments
Content-Type: application/json
device-id: {{device-id}}

{
  "data": {
    "body": "bbbbbbccc"
  }
}


### 후보자 comment list
GET {{server}}/api/v1/candidates/18/comments
Content-Type: application/json
device-id: {{device-id}}


### 
# update comment 
PUT {{server}}/api/v1/comments/2
Content-Type: application/json
device-id: {{device-id}}

{
  "data": {
    "body": "bbbbbbccc"
  }
}

### 
# delete comment 
DELETE {{server}}/api/v1/comments/3
Content-Type: application/json
device-id: {{device-id}}


### 
# my comments
GET {{server}}/api/v1/comments
Content-Type: application/json
device-id: {{device-id}}


###############################################

###
# 도시 
GET {{server}}/api/v1/cities?page=1&per=10
Content-Type: application/json
device-id: {{device-id}}

###
# 선거구 
# GET {{server}}/api/v1/voting_districts?page=1&per=10&x=126.973457&y=37.555465
# GET {{server}}/api/v1/voting_districts?page=1&per=10&x=126.9305023&y=37.4030928
GET {{server}}/api/v1/voting_districts?page=1&per=10
Content-Type: application/json
device-id: {{device-id}}

###
# 후보 list
GET {{server}}/api/v1/candidates?page=1&per=10
# GET {{server}}/api/v1/candidates?page=1&per=10&x=129.014032&y=35.412894
# GET {{server}}/api/v1/candidates?page=1&per=10&x=126.973457&y=37.555465
Content-Type: application/json
device-id: {{device-id}}

###
# 후보 
GET {{server}}/api/v1/candidates/19831
Content-Type: application/json
device-id: {{device-id}}


###
# kakao api
GET https://dapi.kakao.com/v2/local/geo/coord2address.json?x=126.973457&y=37.555465
Authorization: KakaoAK aaebc65e6dd5021b19da8251a4b2adc9





